// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW8rErVB56foW_ZeTuMD-DbBpLwB4xZig',
    appId: '1:478175059788:web:12f52c7c03fd859663f9e9',
    messagingSenderId: '478175059788',
    projectId: 'cardio-auth',
    authDomain: 'cardio-auth.firebaseapp.com',
    storageBucket: 'cardio-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMmH3TnINQBVpJHvxm-ovT487SjTW8BQI',
    appId: '1:478175059788:android:d8c0a91ba3400ed063f9e9',
    messagingSenderId: '478175059788',
    projectId: 'cardio-auth',
    storageBucket: 'cardio-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKF0jE_GcfbvrzsztqZ0o9wTkGsKSmjHk',
    appId: '1:478175059788:ios:aad41f472287234f63f9e9',
    messagingSenderId: '478175059788',
    projectId: 'cardio-auth',
    storageBucket: 'cardio-auth.appspot.com',
    iosClientId: '478175059788-i93unsno0puleh3mjqvjj26lpfnbprkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKF0jE_GcfbvrzsztqZ0o9wTkGsKSmjHk',
    appId: '1:478175059788:ios:aad41f472287234f63f9e9',
    messagingSenderId: '478175059788',
    projectId: 'cardio-auth',
    storageBucket: 'cardio-auth.appspot.com',
    iosClientId: '478175059788-i93unsno0puleh3mjqvjj26lpfnbprkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
